### ISSUE TITLE
pnpm dev fails build prisma

### ISSUE THREAD

**Issue by mkcy3** [reallyMilo/AnnoStamps#18]
Error: Cannot find module '.prisma.client/index'

- README needs instructions with steps on deploying locally
- Switch database provider to sqlite for only local dev 
- Create prisma DB seed scripts and files to seed database with some testing data

**Comment by mkcy3** [comment]
Won't be able to run a local instance of sqlite and postgres for production https://github.com/prisma/prisma/issues/3834

Will have to require a postgres server running locally.

**Comment by reallyMilo** [comment]
Wonder if its pnpm specific? Will try test it. Using npm on my end does build.

Local deploys will need a bit of work with local db and storage since this is all very tied into the current Supabase implementation. Db should be easier but file storage for stamp files and screenshots does use Supabase client.
